### ISSUE TITLE
Handle attachments if needed by Twisted Trac

### ISSUE THREAD

**Issue by danuker** [chevah/trac-to-github#14]
Currently, the ticket migration script does not support attachments, as the Chevah Trac only had 7 of them.

If needed by Twisted Trac, create an attachment scraper, commit the attachments to a GH repo in a branch outside of main, and add links to the attachments either from the description, or ticket comments.

**Comment by adiroiban** [comment]
For reference here is a Trac ticket with attachments https://twistedmatrix.com/trac/ticket/4419

The link to the attach is something like this
https://twistedmatrix.com/trac/attachment/ticket/4419/0002-Deprecate-and-ignore-replies-to-a-NOTICE-event-in-IR.2.patch

with actual file at https://twistedmatrix.com/trac/raw-attachment/ticket/4419/0002-Deprecate-and-ignore-replies-to-a-NOTICE-event-in-IR.2.patch

I can give you access to Twisted trac instance to take a look... I have no idea where these files are stored on disk.

The plan is something like this:

* get all the Trac attachments (wiki and tickets) into a github repo with a certain structure (no need for git-lfs)
*  Publish the files as plain HTTP via GitHub Pages
* Use the links to add comments or description to the migrated tickets

**Comment by danuker** [comment]
Migrating attachments to https://github.com/twisted/twistedmatrix.com-trac-attachments
