### ISSUE TITLE
Preserve all trac ticket metadata in machine readable form

### ISSUE THREAD

**Issue by adiroiban** [chevah/trac-to-github#17]
We should make sure that all the ticket and comments metadata are kept inside the comments in an easy way to be parse by a machine.

We already migrate all the metadata  ... and the original author is included in the comment.

but the author is in a human readable format

I like the current start line

```
trac-5648 ticket was created by @danuker at 2021-06-01 09:02:37Z.
Comment created by pqm at 2021-06-04 09:08:49Z.
```

But maybe we can also have something like this

```
trac-5648 ticket was created by @danuker at 2021-06-01 09:02:37Z.

TRAC TICKET DESCRIPTION HERE

---

trac-id: 1234
author: some-name
reporter: some-name
priority: some-value
milestone: some-value
branch: some-value
```

----

From [here](https://github.com/chevah/trac-to-github/issues/16#issuecomment-1092757816):
 
> The following Trac ticket metadata should be converted into labels
> 
> * status - closed | fixed | new | duplicate | re-open ... etc
> * type - defect | enhancement | task  | release blocker
> * priority
> * component
> 
> Milestone should be assigned to GitHub Milestones
> 
> For all the other "free text" metadata we will only have the as machine readable text:
> 
> * reporter
> * author
> * keywords
> * cc
> * branch
> 
> 
> But we should also include status, type, priority...etc as machine readable.

**Comment by adiroiban** [comment]
and if possible try to make it easy to search the metadata it via github UI.

It looks like this is not working:

key: value

**Comment by danuker** [comment]
> This is why `key2=value2` might be better.

Looks like GH considers `=` and `:` as word delimiters also, and the search does not filter out value1 as a word by itself. For example, these searches should find nothing:

https://github.com/chevah/trac-to-github/issues?q=is%3Aissue+is%3Aopen+key2%3Avalue1
https://github.com/chevah/trac-to-github/issues?q=is%253Aissue+is%253Aopen+key1%253Dvalue2

How about using double underscores? key3__value3 would be a single token (try switching the value with a nonexistent one).

----

> Just make sure to not include spaces

Should I convert spaces in those values to underscores, to be treated as a single token by GitHub?

For example, the `release management` component would become `release_management`, or the `totally automated release infrastructure` milestone would become `totally_automated_release_infrastructure`.

**Comment by adiroiban** [comment]
Instead of underscore ... maybe use '-' ...to reduce the stress on the shift key :)
..and, make it stand out from the key/valye delimiter `key__space-value`

`key__space-value` is ugly.
The only option is using double quotes `is:issue "key3=value1"` so I don't know which one is  better.

**Comment by danuker** [comment]
Looks like quotes do not work for `:` or `=`, this ticket is still returned: https://github.com/chevah/trac-to-github/issues?q=is%3Aissue+is%3Aopen+%22key1%3Dvalue2%22

I will use the underscores as ugly as they are :(

For dashes, it looks like they also returns false positives: searching for `some-` followed by a word that is in this issue, but different than `name` or `value` still yields this result. 

However the quotes work on the dashes, and you might not want to type an entire milestone like `totally automated release infrastructure`, so you could just search for `milestone__totally`.

**Comment by danuker** [comment]
> The following Trac ticket metadata should be converted into labels
> 
>     * status - closed | fixed | new | duplicate | re-open ... etc
> 
>     * type - defect | enhancement | task  | release blocker
> 
>     * priority
> 
>     * component
> 
> 
> Milestone should be assigned to GitHub Milestones
> 
> For all the other "free text" metadata we will only have the as machine readable text:
> 
>     * reporter
> 
>     * author
> 
>     * keywords
> 
>     * cc
> 
>     * branch
> 
> 
> But we should also include status, type, priority...etc as machine readable.

**Comment by danuker** [comment]
Sadly quotes do not work on dashes either: https://github.com/chevah/trac-migration-staging/issues?q=is%3Aissue+is%3Aopen+%22value-unrelated%22

The word "should" is far away from the word "value" in the ticket.

**Comment by danuker** [comment]
Example of CPython migrated ticket: https://github.com/python/cpython/issues/38807

**Comment by danuker** [comment]
Data is preserved. Too much even (allowed every label).
