### ISSUE TITLE
Convert Trac Wiki RST files to GitHub RST

### ISSUE THREAD

**Issue by danuker** [chevah/trac-to-github#2]
Trac has [their specific flavor of RST](https://trac.edgewall.org/wiki/WikiRestructuredText).

Where there are custom `:trac:` directives, replace them with plain relative links useful in the GitHub-imported wiki. 

In addition, avoid mangling non-RST text. The code should leave [TracWiki formatted](https://trac.edgewall.org/wiki/WikiFormatting) files alone.

**Comment by adiroiban** [comment]
Note that in our Trac we use 2 formats for the content... something both on the same page:

* TracWiki markup - https://trac.chevah.com/wiki/WikiStart?action=edit
* RST markup with Trac directives - https://trac.chevah.com/wiki/Development/Python?action=edit
* Mixed of RST with TracWiki macros (see bottom) - https://trac.chevah.com/wiki/Administrative?action=edit

At first, we can use this ticket to convert RST Trac links directives.

Later we should look at converting whole TracWiki pages 

And last, see how to convert TracWiki Macros like - `[[TitleIndex(Administrative/)]]`


TracWiki macro `[[PageOutline]]` can be converted into the RST `content` directive.

**Comment by danuker** [comment]
Merged to master.
